// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

package sh.vers.sdk

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Response body for GET /env_vars and PUT /env_vars.
 */
@Serializable
data class EnvVarsResponse(
    /** All environment variables currently set for the authenticated user. */
    @SerialName("vars")
    val vars: Map<String, kotlinx.serialization.json.JsonElement>,
)

/**
 * Response body for POST /api/v1/repositories
 */
@Serializable
data class CreateRepositoryResponse(
    /** The name of the repository */
    @SerialName("name")
    val name: String,
    /** The ID of the newly created repository */
    @SerialName("repo_id")
    val repo_id: String,
)

/**
 * Public repository information (includes owner org name for namespacing)
 */
@Serializable
data class PublicRepositoryInfo(
    /** When the repository was created */
    @SerialName("created_at")
    val created_at: String,
    /** Optional description */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    /** Full reference: org_name/repo_name */
    @SerialName("full_name")
    val full_name: String,
    /** The repository name */
    @SerialName("name")
    val name: String,
    /** The owning organization's name (namespace) */
    @SerialName("org_name")
    val org_name: String,
    /** The repository's unique identifier */
    @SerialName("repo_id")
    val repo_id: String,
)

/**
 * Response body for GET /api/v1/commit_tags
 */
@Serializable
data class ListTagsResponse(
    /** List of all tags in the user's organization */
    @SerialName("tags")
    val tags: List<TagInfo>,
)

/**
 * Request body for creating a tag within a repository: POST /api/v1/repositories/{repo_name}/tags
 */
@Serializable
data class CreateRepoTagRequest(
    /** The commit ID this tag should point to */
    @SerialName("commit_id")
    val commit_id: String,
    /** Optional description of what this tag represents */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    /** The tag name (e.g. 'latest', 'v1.0') */
    @SerialName("tag_name")
    val tag_name: String,
)

/**
 * Response struct for GET api/v1/system/version
 */
@Serializable
data class OrchestratorVersion(
    /** Executable identifier; should be 'orchestrator' */
    @SerialName("executable_name")
    val executable_name: String,
    /** Current git hash used for the build */
    @SerialName("git_hash")
    val git_hash: String,
    /** Current workspace version */
    @SerialName("workspace_version")
    val workspace_version: String,
)

/**
 */
@Serializable
data class ListCommitsResponse(
    @SerialName("commits")
    val commits: List<CommitInfo>,
    @SerialName("limit")
    val limit: Long,
    @SerialName("offset")
    val offset: Long,
    @SerialName("total")
    val total: Long,
)

/**
 * Response body for `POST /api/v1/deploy`.
 */
@Serializable
data class DeployResponse(
    @SerialName("project_id")
    val project_id: String,
    @SerialName("status")
    val status: String,
    @SerialName("vm_id")
    val vm_id: String,
)

/**
 * Response body for GET /api/v1/repositories/{repo_name}/tags
 */
@Serializable
data class ListRepoTagsResponse(
    /** The repository name */
    @SerialName("repository")
    val repository: String,
    /** List of tags in this repository */
    @SerialName("tags")
    val tags: List<RepoTagInfo>,
)

/**
 */
@Serializable
data class BaseImageInfo(
    @SerialName("base_image_id")
    val base_image_id: String,
    @SerialName("created_at")
    val created_at: String,
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("image_name")
    val image_name: String,
    @SerialName("is_public")
    val is_public: Boolean,
    @SerialName("owner_id")
    val owner_id: String,
    @SerialName("size_mib")
    val size_mib: Int,
    @SerialName("source_type")
    val source_type: String,
)

/**
 * Response body for POST /api/vm/{vm_id}/exec
 */
@Serializable
data class VmExecResponse(
    /** Exec identifier associated with this run. */
    @SerialName("exec_id")
    val exec_id: kotlinx.serialization.json.JsonElement? = null,
    /** Exit code returned by the command. */
    @SerialName("exit_code")
    val exit_code: Int,
    /** UTF-8 decoded stderr (lossy). */
    @SerialName("stderr")
    val stderr: String,
    /** UTF-8 decoded stdout (lossy). */
    @SerialName("stdout")
    val stdout: String,
)

/**
 */
@Serializable
data class CreateBaseImageResponse(
    @SerialName("image_name")
    val image_name: String,
    @SerialName("job_id")
    val job_id: String,
    @SerialName("status")
    val status: String,
)

/**
 * Request body for POST /api/vm/{vm_id}/exec
 */
@Serializable
data class VmExecRequest(
    /** Command and arguments to execute. */
    @SerialName("command")
    val command: List<String>,
    /** Optional environment variables to set for the process. */
    @SerialName("env")
    val env: kotlinx.serialization.json.JsonElement? = null,
    /** Optional exec identifier for tracking. */
    @SerialName("exec_id")
    val exec_id: kotlinx.serialization.json.JsonElement? = null,
    /** Optional stdin payload passed to the command. */
    @SerialName("stdin")
    val stdin: kotlinx.serialization.json.JsonElement? = null,
    /** Timeout in seconds (0 = no timeout). */
    @SerialName("timeout_secs")
    val timeout_secs: kotlinx.serialization.json.JsonElement? = null,
    /** Optional working directory for the command. */
    @SerialName("working_dir")
    val working_dir: kotlinx.serialization.json.JsonElement? = null,
)

/**
 */
@Serializable
data class NewVmsResponse(
    @SerialName("vms")
    val vms: List<NewVmResponse>,
)

/**
 * Request body for POST /api/vm/{vm_id}/exec/stream/attach
 */
@Serializable
data class VmExecStreamAttachRequest(
    /** Optional cursor to resume from (exclusive). If omitted, the full retained backlog is replayed. */
    @SerialName("cursor")
    val cursor: kotlinx.serialization.json.JsonElement? = null,
    /** Identifier of the exec stream session to reattach to. */
    @SerialName("exec_id")
    val exec_id: String,
    /** Start streaming after the latest retained chunk (ignores cursor). */
    @SerialName("from_latest")
    val from_latest: kotlinx.serialization.json.JsonElement? = null,
)

/**
 * Request body for PATCH /api/vm/{vm_id}/state
 */
@Serializable
data class VmUpdateStateRequest(
    /** The requested state for the VM */
    @SerialName("state")
    val state: VmUpdateStateEnum,
)

/**
 */
@Serializable
data class DeleteBaseImageResponse(
    @SerialName("base_image_id")
    val base_image_id: String,
    @SerialName("deleted")
    val deleted: Boolean,
)

/**
 * Response body for GET /api/v1/public/repositories
 */
@Serializable
data class ListPublicRepositoriesResponse(
    @SerialName("repositories")
    val repositories: List<PublicRepositoryInfo>,
)

/**
 * Request body for POST /api/v1/commit_tags
 */
@Serializable
data class CreateTagRequest(
    /** The commit ID this tag should point to */
    @SerialName("commit_id")
    val commit_id: String,
    /** Optional description of what this tag represents */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    /** The name of the tag (alphanumeric, hyphens, underscores, dots, 1-64 chars) */
    @SerialName("tag_name")
    val tag_name: String,
)

/**
 * Response body for GET /api/v1/repositories
 */
@Serializable
data class ListRepositoriesResponse(
    /** List of all repositories in the user's organization */
    @SerialName("repositories")
    val repositories: List<RepositoryInfo>,
)

/**
 * Response body for POST /api/v1/repositories/{repo_name}/tags
 */
@Serializable
data class CreateRepoTagResponse(
    /** The commit ID this tag points to */
    @SerialName("commit_id")
    val commit_id: String,
    /** Full reference in image_name:tag format */
    @SerialName("reference")
    val reference: String,
    /** The ID of the newly created tag */
    @SerialName("tag_id")
    val tag_id: String,
)

/**
 */
@Serializable
data class CommitInfo(
    @SerialName("commit_id")
    val commit_id: String,
    @SerialName("created_at")
    val created_at: String,
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("grandparent_commit_id")
    val grandparent_commit_id: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("is_public")
    val is_public: Boolean,
    @SerialName("name")
    val name: String,
    @SerialName("owner_id")
    val owner_id: String,
    @SerialName("parent_vm_id")
    val parent_vm_id: kotlinx.serialization.json.JsonElement? = null,
)

/**
 * Response body for DELETE /api/v1/domains/{domain_id}
 */
@Serializable
data class DeleteDomainResponse(
    @SerialName("domain_id")
    val domain_id: String,
)

/**
 * Repository information returned in list and get operations
 */
@Serializable
data class RepositoryInfo(
    /** When the repository was created */
    @SerialName("created_at")
    val created_at: String,
    /** Optional description */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    /** Whether this repository is publicly visible */
    @SerialName("is_public")
    val is_public: Boolean,
    /** The repository name */
    @SerialName("name")
    val name: String,
    /** The repository's unique identifier */
    @SerialName("repo_id")
    val repo_id: String,
)

/**
 * Response body for POST /api/keys/validate
 */
@Serializable
data class ValidateKeyResponse(
    @SerialName("message")
    val message: String,
    @SerialName("valid")
    val valid: Boolean,
)

/**
 * Response body for GET /api/vm/{vm_id}/ssh_key
 */
@Serializable
data class VmSshKeyResponse(
    /** The SSH port that will be DNAT'd to the VM's netns (and, in turn, to its TAP device) */
    @SerialName("ssh_port")
    val ssh_port: Int,
    /** Private SSH key in stringified OpenSSH format */
    @SerialName("ssh_private_key")
    val ssh_private_key: String,
)

/**
 * The state of a VM
 */
@Serializable
enum class VmState(val value: String) {
    @SerialName("booting")
    BOOTING("booting"),
    @SerialName("running")
    RUNNING("running"),
    @SerialName("paused")
    PAUSED("paused"),
    @SerialName("sleeping")
    SLEEPING("sleeping"),
    @SerialName("dead")
    DEAD("dead");

    override fun toString(): String = value
}

/**
 * Response body for GET /api/vm/{vm_id}/files
 */
@Serializable
data class VmReadFileResponse(
    /** File contents, base64-encoded. */
    @SerialName("content_b64")
    val content_b64: String,
)

/**
 * Request body for PUT /env_vars — sets (upserts) one or more environment variables.  # Lifecycle model  Environment variables are written to `/etc/environment` inside a VM **once at boot time** via a vsock `WriteFile` request. They are **not** live-synced to running VMs. This is intentional: VMs are ephemeral (create → use → destroy/branch), so env var changes naturally take effect on the next VM.  The `replace` flag exists so callers can atomically express 'I want exactly these variables and nothing else' without having to DELETE each stale key individually. Without it, the only way to remove a variable from future VMs is a separate `DELETE /env_vars/{key}` call per key.
 */
@Serializable
data class SetEnvVarsRequest(
    /** If true, delete all existing variables before writing the new set. This gives 'set exactly these vars' semantics. Default: false (upsert). */
    @SerialName("replace")
    val replace: Boolean? = null,
    /** Key-value pairs to set. Keys must be valid shell identifiers (`^[A-Za-z_][A-Za-z0-9_]*$`, max 256 chars). Values max 8192 chars.  When `replace` is false (default): existing keys are overwritten, keys not mentioned are left untouched (upsert semantics).  When `replace` is true: all existing variables are deleted first, then only the provided vars are stored (replace-all semantics). */
    @SerialName("vars")
    val vars: Map<String, kotlinx.serialization.json.JsonElement>,
)

/**
 * The response body for POST /api/vm/{vm_id}/commit
 */
@Serializable
data class VmCommitResponse(
    /** The UUID of the newly-created commit */
    @SerialName("commit_id")
    val commit_id: String,
)

/**
 * Response body for POST /api/v1/repositories/fork
 */
@Serializable
data class ForkRepositoryResponse(
    /** The new commit in your org (snapshot of the forked VM) */
    @SerialName("commit_id")
    val commit_id: String,
    /** Full reference: repo_name:tag_name */
    @SerialName("reference")
    val reference: String,
    /** The new repository name in your org */
    @SerialName("repo_name")
    val repo_name: String,
    /** The tag name pointing to the forked commit */
    @SerialName("tag_name")
    val tag_name: String,
    /** The new VM that was created from the fork */
    @SerialName("vm_id")
    val vm_id: String,
)

/**
 */
@Serializable
sealed class ImageSourceRequest {
    @Serializable
    @SerialName("image_ref")
    data class ImageRef(
        @SerialName("image_ref")
        val image_ref: String,
        @SerialName("type")
        val type: String
    ) : ImageSourceRequest()

    @Serializable
    @SerialName("bucket")
    data class Bucket(
        @SerialName("bucket")
        val bucket: String,
        @SerialName("key")
        val key: String,
        @SerialName("type")
        val type: String
    ) : ImageSourceRequest()

}

/**
 * Possible options for the state requested in PATCH /api/vm/{vm_id}/state
 */
@Serializable
enum class VmUpdateStateEnum(val value: String) {
    @SerialName("Paused")
    PAUSED("Paused"),
    @SerialName("Running")
    RUNNING("Running");

    override fun toString(): String = value
}

/**
 */
@Serializable
data class ErrorResponse(
    /** Reason of error */
    @SerialName("error")
    val error: String? = null,
    /** Is always: false */
    @SerialName("success")
    val success: Boolean? = null,
)

/**
 * Request body for PATCH /commits/{commit_id}
 */
@Serializable
data class UpdateCommitRequest(
    /** Optional description for the commit. */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("is_public")
    val is_public: Boolean,
    /** Optional human-readable name for the commit. */
    @SerialName("name")
    val name: kotlinx.serialization.json.JsonElement? = null,
)

/**
 * Request body for POST /api/v1/repositories
 */
@Serializable
data class CreateRepositoryRequest(
    /** Optional description of the repository */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    /** The name of the repository (alphanumeric, hyphens, underscores, dots, 1-64 chars) */
    @SerialName("name")
    val name: String,
)

/**
 * Response type for domain operations.
 */
@Serializable
data class DomainResponse(
    @SerialName("created_at")
    val created_at: String,
    @SerialName("domain")
    val domain: String,
    @SerialName("domain_id")
    val domain_id: String,
    @SerialName("vm_id")
    val vm_id: String,
)

/**
 * The request body for POST /api/vm/{vm_id}/commit
 */
@Serializable
data class VmCommitRequest(
    /** If provided, chelsea will use the requested commit UUID. Otherwise, it will generate a UUID itself. */
    @SerialName("commit_id")
    val commit_id: kotlinx.serialization.json.JsonElement? = null,
    /** Optional description for the commit. */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    /** Optional human-readable name for the commit. Defaults to auto-generated name if not provided. */
    @SerialName("name")
    val name: kotlinx.serialization.json.JsonElement? = null,
)

/**
 * Settings for the deploy build pipeline.
 */
@Serializable
data class DeploySettings(
    @SerialName("build_command")
    val build_command: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("install_command")
    val install_command: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("run_command")
    val run_command: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("working_directory")
    val working_directory: kotlinx.serialization.json.JsonElement? = null,
)

/**
 */
@Serializable
data class CreateBaseImageRequest(
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("image_name")
    val image_name: String,
    /** Additional capacity in MiB beyond the actual filesystem size (defaults to 256). The final image size = calculated rootfs size + this value. Set to 0 for minimum possible image size, or higher for more free space. */
    @SerialName("size_mib")
    val size_mib: Int? = null,
    @SerialName("source")
    val source: ImageSourceRequest,
)

/**
 * Request body for POST /api/v1/repositories/fork
 */
@Serializable
data class ForkRepositoryRequest(
    /** Name for the new repository in your org (defaults to source_repo if omitted) */
    @SerialName("repo_name")
    val repo_name: kotlinx.serialization.json.JsonElement? = null,
    /** The organization that owns the source public repository */
    @SerialName("source_org")
    val source_org: String,
    /** The source repository name */
    @SerialName("source_repo")
    val source_repo: String,
    /** The tag to fork (e.g. 'latest', 'v1.0') */
    @SerialName("source_tag")
    val source_tag: String,
    /** Tag name in the new repo (defaults to source_tag if omitted) */
    @SerialName("tag_name")
    val tag_name: kotlinx.serialization.json.JsonElement? = null,
)

/**
 */
@Serializable
data class VmCommitEntity(
    @SerialName("created_at")
    val created_at: String,
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    /** The commit that this commit's parent VM was started from, if any. Intended to optimize traversing the commit tree. */
    @SerialName("grandparent_commit_id")
    val grandparent_commit_id: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("id")
    val id: String,
    /** Whether this commit is publicly accessible (readable/restorable by anyone). */
    @SerialName("is_public")
    val is_public: Boolean,
    @SerialName("name")
    val name: String,
    /** api key id. */
    @SerialName("owner_id")
    val owner_id: String,
    /** The VM that this commit was created from, if any. */
    @SerialName("parent_vm_id")
    val parent_vm_id: kotlinx.serialization.json.JsonElement? = null,
)

/**
 * Tag information returned in list and get operations
 */
@Serializable
data class TagInfo(
    /** The commit ID this tag currently points to */
    @SerialName("commit_id")
    val commit_id: String,
    /** When the tag was created */
    @SerialName("created_at")
    val created_at: String,
    /** Optional description of what this tag represents */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    /** The tag's unique identifier */
    @SerialName("tag_id")
    val tag_id: String,
    /** The name of the tag */
    @SerialName("tag_name")
    val tag_name: String,
    /** When the tag was last updated (moved to different commit or description changed) */
    @SerialName("updated_at")
    val updated_at: String,
)

/**
 * Request body for PUT /api/vm/{vm_id}/files
 */
@Serializable
data class VmWriteFileRequest(
    /** File contents, base64-encoded. */
    @SerialName("content_b64")
    val content_b64: String,
    /** Create parent directories if they don't exist. */
    @SerialName("create_dirs")
    val create_dirs: Boolean? = null,
    /** File mode (e.g. 0644). Defaults to 0644 if omitted. */
    @SerialName("mode")
    val mode: Int? = null,
    /** Destination path on the VM. */
    @SerialName("path")
    val path: String,
)

/**
 * Streams available for exec logging.
 */
@Serializable
enum class VmExecLogStream(val value: String) {
    @SerialName("stdout")
    STDOUT("stdout"),
    @SerialName("stderr")
    STDERR("stderr");

    override fun toString(): String = value
}

/**
 * Individual log entry describing emitted stdout/stderr chunk.
 */
@Serializable
data class VmExecLogEntry(
    /** Base64-encoded bytes from stdout/stderr chunk. */
    @SerialName("data_b64")
    val data_b64: String,
    @SerialName("exec_id")
    val exec_id: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("stream")
    val stream: VmExecLogStream,
    @SerialName("timestamp")
    val timestamp: String,
)

/**
 */
@Serializable
data class LabelVmRequest(
    @SerialName("labels")
    val labels: kotlinx.serialization.json.JsonElement? = null,
)

/**
 * Response for GET /api/v1/vm/{vm_id}/metadata
 */
@Serializable
data class VmMetadataResponse(
    @SerialName("created_at")
    val created_at: String,
    @SerialName("deleted_at")
    val deleted_at: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("grandparent_vm_id")
    val grandparent_vm_id: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("ip")
    val ip: String,
    @SerialName("owner_id")
    val owner_id: String,
    @SerialName("parent_commit_id")
    val parent_commit_id: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("state")
    val state: VmState,
    @SerialName("vm_id")
    val vm_id: String,
)

/**
 * Request body for PATCH /api/v1/repositories/{repo_name}/visibility
 */
@Serializable
data class SetRepositoryVisibilityRequest(
    /** Whether the repository should be publicly visible */
    @SerialName("is_public")
    val is_public: Boolean,
)

/**
 * Request body for PATCH /api/v1/repositories/{repo_name}/tags/{tag_name}
 */
@Serializable
data class UpdateRepoTagRequest(
    /** Optional new commit ID to move the tag to */
    @SerialName("commit_id")
    val commit_id: kotlinx.serialization.json.JsonElement? = null,
    /** Optional new description for the tag. Send `null` to clear. */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
)

/**
 * Struct representing configuration options common to all VMs
 */
@Serializable
data class VmCreateVmConfig(
    /** The disk size, in MiB. */
    @SerialName("fs_size_mib")
    val fs_size_mib: kotlinx.serialization.json.JsonElement? = null,
    /** The filesystem base image name. Currently, must be 'default' */
    @SerialName("image_name")
    val image_name: kotlinx.serialization.json.JsonElement? = null,
    /** The kernel name. Currently, must be 'default.bin' */
    @SerialName("kernel_name")
    val kernel_name: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("labels")
    val labels: kotlinx.serialization.json.JsonElement? = null,
    /** The RAM size, in MiB. */
    @SerialName("mem_size_mib")
    val mem_size_mib: kotlinx.serialization.json.JsonElement? = null,
    /** How many vCPUs to allocate to this VM (and its children) */
    @SerialName("vcpu_count")
    val vcpu_count: kotlinx.serialization.json.JsonElement? = null,
)

/**
 * Response body for new VM requests (new_root, from_commit, branch)
 */
@Serializable
data class NewVmResponse(
    @SerialName("vm_id")
    val vm_id: String,
)

/**
 * Request body for POST /api/v1/vm/from_commit
 */
@Serializable
sealed class FromCommitVmRequest {
    @Serializable
    @SerialName("commit_id")
    data class CommitId(
        @SerialName("commit_id")
        val commit_id: String
    ) : FromCommitVmRequest()

    @Serializable
    @SerialName("tag_name")
    data class TagName(
        @SerialName("tag_name")
        val tag_name: String
    ) : FromCommitVmRequest()

    @Serializable
    @SerialName("ref")
    data class Ref(
        @SerialName("ref")
        val ref: String
    ) : FromCommitVmRequest()

}

/**
 */
@Serializable
data class VM(
    @SerialName("created_at")
    val created_at: String,
    @SerialName("labels")
    val labels: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("owner_id")
    val owner_id: String,
    @SerialName("state")
    val state: VmState,
    @SerialName("vm_id")
    val vm_id: String,
)

/**
 * Request body for POST /api/v1/domains
 */
@Serializable
data class CreateDomainRequest(
    @SerialName("domain")
    val domain: String,
    @SerialName("vm_id")
    val vm_id: String,
)

/**
 * Request body for PATCH /api/v1/commit_tags/{tag_name}  For `description`: - Field absent from JSON → don't change the description - Field present as `null` → clear the description - Field present as `'text'` → set the description to 'text'
 */
@Serializable
data class UpdateTagRequest(
    /** Optional new commit ID to move the tag to */
    @SerialName("commit_id")
    val commit_id: kotlinx.serialization.json.JsonElement? = null,
    /** Optional new description for the tag. Send `null` to clear an existing description. */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
)

/**
 */
@Serializable
data class UploadBaseImageResponse(
    @SerialName("image_name")
    val image_name: String,
    @SerialName("job_id")
    val job_id: String,
    @SerialName("status")
    val status: String,
)

/**
 */
@Serializable
data class BaseImageStatusResponse(
    @SerialName("error_message")
    val error_message: kotlinx.serialization.json.JsonElement? = null,
    @SerialName("image_name")
    val image_name: String,
    @SerialName("size_mib")
    val size_mib: Int,
    @SerialName("status")
    val status: String,
)

/**
 */
@Serializable
data class ListBaseImagesResponse(
    @SerialName("images")
    val images: List<BaseImageInfo>,
    @SerialName("limit")
    val limit: Long,
    @SerialName("offset")
    val offset: Long,
    @SerialName("total")
    val total: Long,
)

/**
 */
@Serializable
data class NewRootRequest(
    @SerialName("vm_config")
    val vm_config: VmCreateVmConfig,
)

/**
 * Request body for PATCH /api/vm/{vm_id}/disk
 */
@Serializable
data class VmResizeDiskRequest(
    /** The new disk size in MiB. Must be strictly greater than the current size. */
    @SerialName("fs_size_mib")
    val fs_size_mib: Int,
)

/**
 * Response body for DELETE /api/vm/{vm_id}
 */
@Serializable
data class VmDeleteResponse(
    @SerialName("vm_id")
    val vm_id: String,
)

/**
 * Response body for POST /api/v1/commit_tags
 */
@Serializable
data class CreateTagResponse(
    /** The commit ID this tag points to */
    @SerialName("commit_id")
    val commit_id: String,
    /** The ID of the newly created tag */
    @SerialName("tag_id")
    val tag_id: String,
    /** The name of the tag */
    @SerialName("tag_name")
    val tag_name: String,
)

/**
 * Request body for `POST /api/v1/deploy`.
 */
@Serializable
data class DeployRequest(
    /** Git branch to clone (defaults to repo default branch). */
    @SerialName("branch")
    val branch: kotlinx.serialization.json.JsonElement? = null,
    /** Optional project name (defaults to repo name). */
    @SerialName("name")
    val name: kotlinx.serialization.json.JsonElement? = null,
    /** GitHub repository in `owner/repo` format. */
    @SerialName("repo")
    val repo: String,
    @SerialName("settings")
    val settings: kotlinx.serialization.json.JsonElement? = null,
)

/**
 * Tag information within a repository context
 */
@Serializable
data class RepoTagInfo(
    /** The commit ID this tag currently points to */
    @SerialName("commit_id")
    val commit_id: String,
    /** When the tag was created */
    @SerialName("created_at")
    val created_at: String,
    /** Optional description */
    @SerialName("description")
    val description: kotlinx.serialization.json.JsonElement? = null,
    /** Full reference in image_name:tag format */
    @SerialName("reference")
    val reference: String,
    /** The tag's unique identifier */
    @SerialName("tag_id")
    val tag_id: String,
    /** The tag name */
    @SerialName("tag_name")
    val tag_name: String,
    /** When the tag was last updated */
    @SerialName("updated_at")
    val updated_at: String,
)

/**
 * Response for exec log tail requests.
 */
@Serializable
data class VmExecLogResponse(
    /** Returned log entries. */
    @SerialName("entries")
    val entries: List<VmExecLogEntry>,
    /** True when the end of file was reached. */
    @SerialName("eof")
    val eof: Boolean,
    /** Next byte offset to continue from. */
    @SerialName("next_offset")
    val next_offset: Long,
)


// ── Params types for operations with query parameters ───────────────

data class ResizeVmDiskParams(
    /** If true, return an error immediately if the VM is still booting. Default: false */
    val skip_wait_boot: Boolean? = null,
)

data class CreateNewRootVmParams(
    /** If true, wait for the newly-created VM to finish booting before returning. Default: false. */
    val wait_boot: Boolean? = null,
)

data class VmLogsParams(
    /** Byte offset into the log file (default: 0) */
    val offset: Long? = null,
    /** Maximum number of log entries to return */
    val max_entries: Long? = null,
    /** Filter by 'stdout' or 'stderr' */
    val stream: String? = null,
)

data class BranchByRefParams(
    /** Number of VMs to branch (optional; default 1) */
    val count: Long? = null,
)

data class BranchByTagParams(
    /** Number of VMs to branch (optional; default 1) */
    val count: Long? = null,
)

data class BranchVmParams(
    /** If true, keep VM paused after commit. Only applicable when branching a VM ID. */
    val keep_paused: Boolean? = null,
    /** If true, immediately return an error if VM is booting instead of waiting. Only applicable when branching a VM ID. */
    val skip_wait_boot: Boolean? = null,
    /** Number of VMs to branch (optional; default 1) */
    val count: Long? = null,
)

data class UpdateVmStateParams(
    /** If true, error immediately if the VM is not finished booting. Defaults to false */
    val skip_wait_boot: Boolean? = null,
)

data class DeleteVmParams(
    /** If true, return an error immediately if the VM is still booting. Default: false */
    val skip_wait_boot: Boolean? = null,
)

data class BranchByVmParams(
    /** If true, keep VM paused after commit */
    val keep_paused: Boolean? = null,
    /** If true, immediately return an error if VM is booting instead of waiting */
    val skip_wait_boot: Boolean? = null,
    /** Number of VMs to branch (optional; default 1) */
    val count: Long? = null,
)

data class CommitVmParams(
    /** If true, keep VM paused after commit */
    val keep_paused: Boolean? = null,
    /** If true, return an error immediately if the VM is still booting. Default: false */
    val skip_wait_boot: Boolean? = null,
)

data class ListDomainsParams(
    /** Filter by VM ID */
    val vm_id: String? = null,
)

data class ReadFileVmParams(
    /** Absolute path of the file to read */
    val path: String? = null,
)

data class BranchByCommitParams(
    /** Number of VMs to branch (optional; default 1) */
    val count: Long? = null,
)

