// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

package sh.vers.sdk

/**
 * Per-request options that override client defaults.
 *
 * @param headers Additional headers to send with the request.
 * @param timeout Request timeout in seconds. Overrides the client-level timeout.
 */
data class RequestOptions(
    val headers: Map<String, String>? = null,
    val timeout: Long? = null,
)
