// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

package sh.vers.sdk

import kotlinx.coroutines.delay
import kotlinx.serialization.json.Json
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.time.Duration
import java.util.UUID
import java.util.logging.Level
import java.util.logging.Logger
import kotlin.math.min
import kotlin.math.pow
import kotlin.random.Random

/**
 * Client for Orchestrator Control Plane API.
 *
 * @param baseUrl   Base URL for the API. Defaults to VERS_BASE_URL env var or https://api.vers.sh.
 * @param apiKey    Bearer token for authentication. Defaults to VERS_API_KEY env var.
 * @param maxRetries Maximum number of retries for failed requests (default 2).
 * @param timeout   Request timeout in seconds (default 30).
 */
class VersSdkClient(
    private val baseUrl: String = System.getenv("VERS_BASE_URL") ?: "https://api.vers.sh",
    private val apiKey: String? = System.getenv("VERS_API_KEY"),
    private val maxRetries: Int = 2,
    private val timeout: Long = 30,
    private val headers: Map<String, String> = emptyMap(),
) : AutoCloseable {

    private val logger: Logger = Logger.getLogger("vers-sdk")

    private val json: Json = Json {
        ignoreUnknownKeys = true
        encodeDefaults = true
        isLenient = true
    }

    private val httpClient: HttpClient = HttpClient.newBuilder()
        .connectTimeout(Duration.ofSeconds(timeout))
        .build()

    private val userAgent: String = "vers-sdk/0.1.8 kotlin/${System.getProperty("java.version")} ${System.getProperty("os.name").lowercase()}/${System.getProperty("os.arch")}"

    init {
        val envLevel = System.getenv("VERS_LOG") ?: "warn"
        logger.level = when (envLevel.lowercase()) {
            "debug" -> Level.FINE
            "info" -> Level.INFO
            "warn" -> Level.WARNING
            "error" -> Level.SEVERE
            "off" -> Level.OFF
            else -> Level.WARNING
        }
    }

    companion object {
        private val RETRYABLE_STATUS_CODES = setOf(408, 409, 429)

        private fun isRetryableStatus(status: Int): Boolean =
            status >= 500 || status in RETRYABLE_STATUS_CODES

        private fun retryDelay(attempt: Int): Long {
            val base = 500L * (1L shl attempt) // 0.5s * 2^attempt
            val jitter = (Random.nextDouble() * base * 0.25).toLong()
            return base + jitter
        }

        private fun parseRetryAfter(value: String?): Long? {
            if (value == null) return null
            return try {
                val seconds = value.toDouble()
                val ms = (seconds.coerceIn(0.0, 60.0) * 1000).toLong()
                ms
            } catch (_: NumberFormatException) {
                null
            }
        }
    }

    private fun buildRequest(method: String, path: String, body: String? = null, options: RequestOptions? = null): HttpRequest {
        val uri = URI.create("${baseUrl.trimEnd('/')}$path")
        val builder = HttpRequest.newBuilder(uri)

        // Default headers
        builder.header("User-Agent", userAgent)
        builder.header("Content-Type", "application/json")
        builder.header("Accept", "application/json")

        // Auth
        if (apiKey != null) {
            builder.header("Authorization", "Bearer $apiKey")
        }

        // Client-level custom headers
        for ((key, value) in headers) {
            builder.header(key, value)
        }

        // Idempotency key for mutating methods
        if (method.uppercase() in listOf("POST", "PUT", "PATCH", "DELETE")) {
            builder.header("X-Idempotency-Key", UUID.randomUUID().toString())
        }

        // Per-request header overrides
        options?.headers?.forEach { (key, value) ->
            builder.header(key, value)
        }

        // Timeout
        val effectiveTimeout = options?.timeout ?: timeout
        builder.timeout(Duration.ofSeconds(effectiveTimeout))

        // Method + body
        val bodyPublisher = if (body != null) {
            HttpRequest.BodyPublishers.ofString(body)
        } else {
            HttpRequest.BodyPublishers.noBody()
        }
        builder.method(method.uppercase(), bodyPublisher)

        return builder.build()
    }

    private suspend fun request(
        method: String,
        path: String,
        body: String? = null,
        options: RequestOptions? = null,
    ): HttpResponse<String> {
        logger.fine("request: $method $path")

        var lastException: Exception? = null
        for (attempt in 0..maxRetries) {
            if (attempt > 0) {
                logger.info("retry attempt $attempt/$maxRetries for $method $path")
                delay(retryDelay(attempt - 1))
            }

            try {
                val request = buildRequest(method, path, body, options)
                val response = httpClient.send(request, HttpResponse.BodyHandlers.ofString())
                logger.fine("response: ${response.statusCode()} for $method $path")

                if (isRetryableStatus(response.statusCode()) && attempt < maxRetries) {
                    val retryAfterMs = parseRetryAfter(response.headers().firstValue("retry-after").orElse(null))
                    if (retryAfterMs != null) {
                        logger.info("retry attempt ${attempt + 1}/$maxRetries for $method $path (retry-after: ${retryAfterMs}ms)")
                        delay(retryAfterMs)
                    }
                    lastException = APIError.generate(
                        status = response.statusCode(),
                        body = response.body(),
                        headers = response.headers().map().mapValues { it.value.firstOrNull() ?: "" },
                    )
                    continue
                }

                if (response.statusCode() !in 200..299) {
                    throw APIError.generate(
                        status = response.statusCode(),
                        body = response.body(),
                        headers = response.headers().map().mapValues { it.value.firstOrNull() ?: "" },
                    )
                }

                return response
            } catch (e: APIError) {
                throw e
            } catch (e: java.net.ConnectException) {
                logger.severe("connection error: $method $path - ${e.message}")
                if (attempt == maxRetries) throw APIConnectionError(cause = e)
                lastException = APIConnectionError(cause = e)
            } catch (e: java.net.http.HttpTimeoutException) {
                logger.severe("timeout: $method $path - ${e.message}")
                if (attempt == maxRetries) throw APIConnectionTimeoutError(cause = e)
                lastException = APIConnectionTimeoutError(cause = e)
            } catch (e: java.io.IOException) {
                logger.severe("io error: $method $path - ${e.message}")
                if (attempt == maxRetries) throw APIConnectionError(cause = e)
                lastException = APIConnectionError(cause = e)
            }
        }
        throw lastException ?: APIConnectionError(message = "Request failed after $maxRetries retries")
    }

    // ── API Operations ──────────────────────────────────────────────────

    /**
     * 
     */
    suspend fun vmStatus(vm_id: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/status", vm_id)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun resizeVmDisk(vm_id: String, body: Map<String, Any?>? = null, params: ResizeVmDiskParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/disk", vm_id)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.skip_wait_boot != null) queryParts.add("skip_wait_boot=${java.net.URLEncoder.encode(params.skip_wait_boot.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("PATCH", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun execVmStreamAttach(vm_id: String, body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/exec/stream/attach", vm_id)
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listVms(options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/vms"
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun createNewRootVm(body: Map<String, Any?>? = null, params: CreateNewRootVmParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/vm/new_root"
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.wait_boot != null) queryParts.add("wait_boot=${java.net.URLEncoder.encode(params.wait_boot.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun vmLogs(vm_id: String, params: VmLogsParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/logs", vm_id)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.offset != null) queryParts.add("offset=${java.net.URLEncoder.encode(params.offset.toString(), "UTF-8")}")
            if (params.max_entries != null) queryParts.add("max_entries=${java.net.URLEncoder.encode(params.max_entries.toString(), "UTF-8")}")
            if (params.stream != null) queryParts.add("stream=${java.net.URLEncoder.encode(params.stream.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val bodyStr: String? = null
        val response = request("GET", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun branchByRef(repo_name: String, tag_name: String, body: Map<String, Any?>? = null, params: BranchByRefParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/branch/by_ref/%s/%s", repo_name, tag_name)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.count != null) queryParts.add("count=${java.net.URLEncoder.encode(params.count.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun labelVm(vm_id: String, body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/label", vm_id)
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("PATCH", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listPublicCommits(options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/commits/public"
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun getImageStatus(image_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/images/%s/status", image_name)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listPublicRepoTags(org_name: String, repo_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/public/repositories/%s/%s/tags", org_name, repo_name)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun versionHandler(options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/system/version"
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun branchByTag(tag_name: String, body: Map<String, Any?>? = null, params: BranchByTagParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/branch/by_tag/%s", tag_name)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.count != null) queryParts.add("count=${java.net.URLEncoder.encode(params.count.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun getRepoTag(repo_name: String, tag_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/repositories/%s/tags/%s", repo_name, tag_name)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun deleteRepoTag(repo_name: String, tag_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/repositories/%s/tags/%s", repo_name, tag_name)
        val bodyStr: String? = null
        val response = request("DELETE", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun updateRepoTag(repo_name: String, tag_name: String, body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/repositories/%s/tags/%s", repo_name, tag_name)
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("PATCH", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun branchVm(vm_or_commit_id: String, body: Map<String, Any?>? = null, params: BranchVmParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/branch", vm_or_commit_id)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.keep_paused != null) queryParts.add("keep_paused=${java.net.URLEncoder.encode(params.keep_paused.toString(), "UTF-8")}")
            if (params.skip_wait_boot != null) queryParts.add("skip_wait_boot=${java.net.URLEncoder.encode(params.skip_wait_boot.toString(), "UTF-8")}")
            if (params.count != null) queryParts.add("count=${java.net.URLEncoder.encode(params.count.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun getRepository(repo_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/repositories/%s", repo_name)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun deleteRepository(repo_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/repositories/%s", repo_name)
        val bodyStr: String? = null
        val response = request("DELETE", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listParentCommits(commit_id: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/commits/%s/parents", commit_id)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun validateKey(body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/keys/validate"
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun forkRepository(body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/repositories/fork"
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listRepositories(options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/repositories"
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun createRepository(body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/repositories"
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun updateVmState(vm_id: String, body: Map<String, Any?>? = null, params: UpdateVmStateParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/state", vm_id)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.skip_wait_boot != null) queryParts.add("skip_wait_boot=${java.net.URLEncoder.encode(params.skip_wait_boot.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("PATCH", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun createImage(body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/images/create"
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun restoreFromCommit(body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/vm/from_commit"
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun getDomain(domain_id: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/domains/%s", domain_id)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun deleteDomain(domain_id: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/domains/%s", domain_id)
        val bodyStr: String? = null
        val response = request("DELETE", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listTags(options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/commit_tags"
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun createTag(body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/commit_tags"
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listPublicRepositories(options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/public/repositories"
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun getPublicRepoTag(org_name: String, repo_name: String, tag_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/public/repositories/%s/%s/tags/%s", org_name, repo_name, tag_name)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun getVmMetadata(vm_id: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/metadata", vm_id)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listEnvVars(options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/env_vars"
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun setEnvVars(body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/env_vars"
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("PUT", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun deleteVm(vm_id: String, params: DeleteVmParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s", vm_id)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.skip_wait_boot != null) queryParts.add("skip_wait_boot=${java.net.URLEncoder.encode(params.skip_wait_boot.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val bodyStr: String? = null
        val response = request("DELETE", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listCommits(options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/commits"
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun getTag(tag_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/commit_tags/%s", tag_name)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun deleteTag(tag_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/commit_tags/%s", tag_name)
        val bodyStr: String? = null
        val response = request("DELETE", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun updateTag(tag_name: String, body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/commit_tags/%s", tag_name)
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("PATCH", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun branchByVm(vm_id: String, body: Map<String, Any?>? = null, params: BranchByVmParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/branch/by_vm/%s", vm_id)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.keep_paused != null) queryParts.add("keep_paused=${java.net.URLEncoder.encode(params.keep_paused.toString(), "UTF-8")}")
            if (params.skip_wait_boot != null) queryParts.add("skip_wait_boot=${java.net.URLEncoder.encode(params.skip_wait_boot.toString(), "UTF-8")}")
            if (params.count != null) queryParts.add("count=${java.net.URLEncoder.encode(params.count.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun deleteEnvVar(key: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/env_vars/%s", key)
        val bodyStr: String? = null
        val response = request("DELETE", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun deleteImage(base_image_id: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/images/images/%s", base_image_id)
        val bodyStr: String? = null
        val response = request("DELETE", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun commitVm(vm_id: String, body: Map<String, Any?>? = null, params: CommitVmParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/commit", vm_id)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.keep_paused != null) queryParts.add("keep_paused=${java.net.URLEncoder.encode(params.keep_paused.toString(), "UTF-8")}")
            if (params.skip_wait_boot != null) queryParts.add("skip_wait_boot=${java.net.URLEncoder.encode(params.skip_wait_boot.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun deleteCommit(commit_id: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/commits/%s", commit_id)
        val bodyStr: String? = null
        val response = request("DELETE", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun updateCommit(commit_id: String, body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/commits/%s", commit_id)
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("PATCH", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listRepoTags(repo_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/repositories/%s/tags", repo_name)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun createRepoTag(repo_name: String, body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/repositories/%s/tags", repo_name)
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * Deploy a GitHub repository to a new Vers project.
     */
    suspend fun deployHandler(body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/deploy"
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun execVm(vm_id: String, body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/exec", vm_id)
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun setRepositoryVisibility(repo_name: String, body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/repositories/%s/visibility", repo_name)
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("PATCH", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun execVmStream(vm_id: String, body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/exec/stream", vm_id)
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listDomains(params: ListDomainsParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/domains"
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.vm_id != null) queryParts.add("vm_id=${java.net.URLEncoder.encode(params.vm_id.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val bodyStr: String? = null
        val response = request("GET", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun createDomain(body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/domains"
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun sshKey(vm_id: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/ssh_key", vm_id)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun listImages(options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/images"
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun readFileVm(vm_id: String, params: ReadFileVmParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/files", vm_id)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.path != null) queryParts.add("path=${java.net.URLEncoder.encode(params.path.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val bodyStr: String? = null
        val response = request("GET", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun writeFileVm(vm_id: String, body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/%s/files", vm_id)
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("PUT", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun uploadImage(body: Map<String, Any?>? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = "/api/v1/images/upload"
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun getPublicRepository(org_name: String, repo_name: String, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/public/repositories/%s/%s", org_name, repo_name)
        val bodyStr: String? = null
        val response = request("GET", path, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    /**
     * 
     */
    suspend fun branchByCommit(commit_id: String, body: Map<String, Any?>? = null, params: BranchByCommitParams? = null, options: RequestOptions? = null): Map<String, Any?> {
        val path = String.format("/api/v1/vm/branch/by_commit/%s", commit_id)
        val queryParts = mutableListOf<String>()
        if (params != null) {
            if (params.count != null) queryParts.add("count=${java.net.URLEncoder.encode(params.count.toString(), "UTF-8")}")
        }
        val fullPath = if (queryParts.isNotEmpty()) "$path?${queryParts.joinToString("&")}" else path
        val jsonBody = json.encodeToString(kotlinx.serialization.serializer<Map<String, kotlinx.serialization.json.JsonElement>>(), emptyMap()) // placeholder
        val bodyStr = if (body != null) buildJsonBody(body) else null
        val response = request("POST", fullPath, bodyStr, options)
        @Suppress("UNCHECKED_CAST")
        return json.decodeFromString<Map<String, kotlinx.serialization.json.JsonElement>>(response.body()) as Map<String, Any?>
    }

    private fun buildJsonBody(map: Map<String, Any?>): String {
        val sb = StringBuilder("{")
        var first = true
        for ((key, value) in map) {
            if (value == null) continue
            if (!first) sb.append(",")
            first = false
            sb.append("\"$key\":")
            when (value) {
                is String -> sb.append("\"${value.replace("\"", "\\\"")}\"")
                is Number -> sb.append(value)
                is Boolean -> sb.append(value)
                is Map<*, *> -> sb.append(buildJsonBody(@Suppress("UNCHECKED_CAST") (value as Map<String, Any?>)))
                is List<*> -> {
                    sb.append("[")
                    value.forEachIndexed { i, v ->
                        if (i > 0) sb.append(",")
                        when (v) {
                            is String -> sb.append("\"${v.replace("\"", "\\\"")}\"")
                            is Number -> sb.append(v)
                            is Boolean -> sb.append(v)
                            is Map<*, *> -> sb.append(buildJsonBody(@Suppress("UNCHECKED_CAST") (v as Map<String, Any?>)))
                            else -> sb.append("\"$v\"")
                        }
                    }
                    sb.append("]")
                }
                else -> sb.append("\"$value\"")
            }
        }
        sb.append("}")
        return sb.toString()
    }

    override fun close() {
        // HttpClient does not require explicit close in Java 11+
    }
}
